// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iefnqtzbpruuhoxgmtcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllZm5xdHpicHJ1dWhveGdtdGN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjIwNTIsImV4cCI6MjA2NjU5ODA1Mn0.I38aoi0WumY4wYnQwfVR2cZiQ6aGS-6Boi4lnIPvhXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);